# Generated by Django 4.0.4 on 2022-05-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_id_alter_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                choices=[("full", "Полный пакет"), ("free", "Бесплатный пакет")],
                default="free",
                max_length=30,
            ),
        ),
    ]
