# Generated by Django 5.0.6 on 2024-07-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='user_images/default_us.png', upload_to='user_images'),
        ),
    ]
